// Generated by gencpp from file pick_objects/my_robot_pose.msg
// DO NOT EDIT!


#ifndef PICK_OBJECTS_MESSAGE_MY_ROBOT_POSE_H
#define PICK_OBJECTS_MESSAGE_MY_ROBOT_POSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pick_objects
{
template <class ContainerAllocator>
struct my_robot_pose_
{
  typedef my_robot_pose_<ContainerAllocator> Type;

  my_robot_pose_()
    : pose_x(0.0)
    , pose_y(0.0)  {
    }
  my_robot_pose_(const ContainerAllocator& _alloc)
    : pose_x(0.0)
    , pose_y(0.0)  {
  (void)_alloc;
    }



   typedef double _pose_x_type;
  _pose_x_type pose_x;

   typedef double _pose_y_type;
  _pose_y_type pose_y;





  typedef boost::shared_ptr< ::pick_objects::my_robot_pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pick_objects::my_robot_pose_<ContainerAllocator> const> ConstPtr;

}; // struct my_robot_pose_

typedef ::pick_objects::my_robot_pose_<std::allocator<void> > my_robot_pose;

typedef boost::shared_ptr< ::pick_objects::my_robot_pose > my_robot_posePtr;
typedef boost::shared_ptr< ::pick_objects::my_robot_pose const> my_robot_poseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pick_objects::my_robot_pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pick_objects::my_robot_pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pick_objects

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'pick_objects': ['/home/robond/home/workspace/catkin_ws/src/pick_objects/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pick_objects::my_robot_pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pick_objects::my_robot_pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_objects::my_robot_pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_objects::my_robot_pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_objects::my_robot_pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_objects::my_robot_pose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pick_objects::my_robot_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b2557794f14ba3d93612601bd953900c";
  }

  static const char* value(const ::pick_objects::my_robot_pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb2557794f14ba3d9ULL;
  static const uint64_t static_value2 = 0x3612601bd953900cULL;
};

template<class ContainerAllocator>
struct DataType< ::pick_objects::my_robot_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pick_objects/my_robot_pose";
  }

  static const char* value(const ::pick_objects::my_robot_pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pick_objects::my_robot_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 pose_x\n\
float64 pose_y\n\
";
  }

  static const char* value(const ::pick_objects::my_robot_pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pick_objects::my_robot_pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose_x);
      stream.next(m.pose_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct my_robot_pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pick_objects::my_robot_pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::pick_objects::my_robot_pose_<ContainerAllocator>& v)
  {
    s << indent << "pose_x: ";
    Printer<double>::stream(s, indent + "  ", v.pose_x);
    s << indent << "pose_y: ";
    Printer<double>::stream(s, indent + "  ", v.pose_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PICK_OBJECTS_MESSAGE_MY_ROBOT_POSE_H
