// Generated by gencpp from file pick_objects/my_robot_poseResponse.msg
// DO NOT EDIT!


#ifndef PICK_OBJECTS_MESSAGE_MY_ROBOT_POSERESPONSE_H
#define PICK_OBJECTS_MESSAGE_MY_ROBOT_POSERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pick_objects
{
template <class ContainerAllocator>
struct my_robot_poseResponse_
{
  typedef my_robot_poseResponse_<ContainerAllocator> Type;

  my_robot_poseResponse_()
    {
    }
  my_robot_poseResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::pick_objects::my_robot_poseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pick_objects::my_robot_poseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct my_robot_poseResponse_

typedef ::pick_objects::my_robot_poseResponse_<std::allocator<void> > my_robot_poseResponse;

typedef boost::shared_ptr< ::pick_objects::my_robot_poseResponse > my_robot_poseResponsePtr;
typedef boost::shared_ptr< ::pick_objects::my_robot_poseResponse const> my_robot_poseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pick_objects::my_robot_poseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pick_objects::my_robot_poseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pick_objects

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pick_objects::my_robot_poseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pick_objects::my_robot_poseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_objects::my_robot_poseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pick_objects::my_robot_poseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_objects::my_robot_poseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pick_objects::my_robot_poseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pick_objects::my_robot_poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::pick_objects::my_robot_poseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::pick_objects::my_robot_poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pick_objects/my_robot_poseResponse";
  }

  static const char* value(const ::pick_objects::my_robot_poseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pick_objects::my_robot_poseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::pick_objects::my_robot_poseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pick_objects::my_robot_poseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct my_robot_poseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pick_objects::my_robot_poseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::pick_objects::my_robot_poseResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // PICK_OBJECTS_MESSAGE_MY_ROBOT_POSERESPONSE_H
