controller_frequency: 10

TrajectoryPlannerROS:
  max_vel_x: 1.5 #0.5
  min_vel_x: -0.1 #0.01
  max_vel_theta: 0.785398 #1.5

  min_in_place_vel_theta: 0.314

  acc_lim_theta: 1.5708
  acc_lim_x: 1.5708
  acc_lim_y: 1.5708

  sim_time: 4.0

  vx_samples: 4.0
  vtheta_samples: 50.0

  pdist_scale: 0.6 #0.6
  gdist_scale: 0.8 #0.8
  occdist_scale: 0.2

  holonomic_robot: false

  heading_scoring: false
  # heading_lookahead: 1.0
  
  meter_scoring: true
  shutdown_costmaps: false
  
  controller_frequency: 20.0
  controller_patience: 15.0
  
 
  planner_frequency: 10.0
  planner_patience: 5.0
 
  oscillation_timeout: 0.0
  oscillation_distance: 0.5

  recovery_behavior_enabled: true
  clearing_rotation_allowed: true
   
 

